# Generated by Django 5.0.7 on 2024-07-24 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_is_sale_product_sale_price_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 22, 41, 13, 698975)),
        ),
    ]
